/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutAuthenticatedHomeRouteImport } from './routes/_layout/_authenticated/home'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedHomeRoute = LayoutAuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutAuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LayoutLoginRoute
  '/home': typeof LayoutAuthenticatedHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/login': typeof LayoutLoginRoute
  '/home': typeof LayoutAuthenticatedHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/home': typeof LayoutAuthenticatedHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/home'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/login'
    | '/_layout/'
    | '/_layout/_authenticated/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/home': {
      id: '/_layout/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutAuthenticatedHomeRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
  }
}

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedHomeRoute: typeof LayoutAuthenticatedHomeRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedHomeRoute: LayoutAuthenticatedHomeRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
