/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutConfigRouteImport } from './routes/_layout/config'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutAppsIndexRouteImport } from './routes/_layout/apps/index'
import { Route as LayoutAuthenticatedSettingsRouteImport } from './routes/_layout/_authenticated/settings'
import { Route as LayoutAuthenticatedHomeRouteImport } from './routes/_layout/_authenticated/home'
import { Route as LayoutAuthenticatedAdminRouteImport } from './routes/_layout/_authenticated/_admin'
import { Route as LayoutAppsAccountIdIndexRouteImport } from './routes/_layout/apps/$accountId/index'
import { Route as LayoutAuthenticatedProjectsIndexRouteImport } from './routes/_layout/_authenticated/projects/index'
import { Route as LayoutAuthenticatedOrganizationsIndexRouteImport } from './routes/_layout/_authenticated/organizations/index'
import { Route as LayoutAppsAccountIdGatewayIdRouteImport } from './routes/_layout/apps/$accountId/$gatewayId'
import { Route as LayoutAuthenticatedProjectsNewRouteImport } from './routes/_layout/_authenticated/projects/new'
import { Route as LayoutAuthenticatedProjectsIdRouteImport } from './routes/_layout/_authenticated/projects/$id'
import { Route as LayoutAuthenticatedOrganizationsNewRouteImport } from './routes/_layout/_authenticated/organizations/new'
import { Route as LayoutAuthenticatedOrganizationsIdRouteImport } from './routes/_layout/_authenticated/organizations/$id'
import { Route as LayoutAuthenticatedAdminDashboardRouteImport } from './routes/_layout/_authenticated/_admin/dashboard'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConfigRoute = LayoutConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppsIndexRoute = LayoutAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedSettingsRoute =
  LayoutAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedHomeRoute = LayoutAuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutAuthenticatedRoute,
} as any)
const LayoutAuthenticatedAdminRoute =
  LayoutAuthenticatedAdminRouteImport.update({
    id: '/_admin',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAppsAccountIdIndexRoute =
  LayoutAppsAccountIdIndexRouteImport.update({
    id: '/apps/$accountId/',
    path: '/apps/$accountId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAuthenticatedProjectsIndexRoute =
  LayoutAuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOrganizationsIndexRoute =
  LayoutAuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAppsAccountIdGatewayIdRoute =
  LayoutAppsAccountIdGatewayIdRouteImport.update({
    id: '/apps/$accountId/$gatewayId',
    path: '/apps/$accountId/$gatewayId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAuthenticatedProjectsNewRoute =
  LayoutAuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedProjectsIdRoute =
  LayoutAuthenticatedProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOrganizationsNewRoute =
  LayoutAuthenticatedOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOrganizationsIdRoute =
  LayoutAuthenticatedOrganizationsIdRouteImport.update({
    id: '/organizations/$id',
    path: '/organizations/$id',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAdminDashboardRoute =
  LayoutAuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/config': typeof LayoutConfigRoute
  '/login': typeof LayoutLoginRoute
  '/home': typeof LayoutAuthenticatedHomeRoute
  '/settings': typeof LayoutAuthenticatedSettingsRoute
  '/apps/': typeof LayoutAppsIndexRoute
  '/dashboard': typeof LayoutAuthenticatedAdminDashboardRoute
  '/organizations/$id': typeof LayoutAuthenticatedOrganizationsIdRoute
  '/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/projects/$id': typeof LayoutAuthenticatedProjectsIdRoute
  '/projects/new': typeof LayoutAuthenticatedProjectsNewRoute
  '/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/organizations/': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/projects/': typeof LayoutAuthenticatedProjectsIndexRoute
  '/apps/$accountId/': typeof LayoutAppsAccountIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/config': typeof LayoutConfigRoute
  '/login': typeof LayoutLoginRoute
  '/home': typeof LayoutAuthenticatedHomeRoute
  '/settings': typeof LayoutAuthenticatedSettingsRoute
  '/apps': typeof LayoutAppsIndexRoute
  '/dashboard': typeof LayoutAuthenticatedAdminDashboardRoute
  '/organizations/$id': typeof LayoutAuthenticatedOrganizationsIdRoute
  '/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/projects/$id': typeof LayoutAuthenticatedProjectsIdRoute
  '/projects/new': typeof LayoutAuthenticatedProjectsNewRoute
  '/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/organizations': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/projects': typeof LayoutAuthenticatedProjectsIndexRoute
  '/apps/$accountId': typeof LayoutAppsAccountIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/config': typeof LayoutConfigRoute
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/_admin': typeof LayoutAuthenticatedAdminRouteWithChildren
  '/_layout/_authenticated/home': typeof LayoutAuthenticatedHomeRoute
  '/_layout/_authenticated/settings': typeof LayoutAuthenticatedSettingsRoute
  '/_layout/apps/': typeof LayoutAppsIndexRoute
  '/_layout/_authenticated/_admin/dashboard': typeof LayoutAuthenticatedAdminDashboardRoute
  '/_layout/_authenticated/organizations/$id': typeof LayoutAuthenticatedOrganizationsIdRoute
  '/_layout/_authenticated/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/_layout/_authenticated/projects/$id': typeof LayoutAuthenticatedProjectsIdRoute
  '/_layout/_authenticated/projects/new': typeof LayoutAuthenticatedProjectsNewRoute
  '/_layout/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/_layout/_authenticated/organizations/': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/_layout/_authenticated/projects/': typeof LayoutAuthenticatedProjectsIndexRoute
  '/_layout/apps/$accountId/': typeof LayoutAppsAccountIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/config'
    | '/login'
    | '/home'
    | '/settings'
    | '/apps/'
    | '/dashboard'
    | '/organizations/$id'
    | '/organizations/new'
    | '/projects/$id'
    | '/projects/new'
    | '/apps/$accountId/$gatewayId'
    | '/organizations/'
    | '/projects/'
    | '/apps/$accountId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/config'
    | '/login'
    | '/home'
    | '/settings'
    | '/apps'
    | '/dashboard'
    | '/organizations/$id'
    | '/organizations/new'
    | '/projects/$id'
    | '/projects/new'
    | '/apps/$accountId/$gatewayId'
    | '/organizations'
    | '/projects'
    | '/apps/$accountId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/about'
    | '/_layout/config'
    | '/_layout/login'
    | '/_layout/'
    | '/_layout/_authenticated/_admin'
    | '/_layout/_authenticated/home'
    | '/_layout/_authenticated/settings'
    | '/_layout/apps/'
    | '/_layout/_authenticated/_admin/dashboard'
    | '/_layout/_authenticated/organizations/$id'
    | '/_layout/_authenticated/organizations/new'
    | '/_layout/_authenticated/projects/$id'
    | '/_layout/_authenticated/projects/new'
    | '/_layout/apps/$accountId/$gatewayId'
    | '/_layout/_authenticated/organizations/'
    | '/_layout/_authenticated/projects/'
    | '/_layout/apps/$accountId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/config': {
      id: '/_layout/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof LayoutConfigRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/': {
      id: '/_layout/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof LayoutAppsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/settings': {
      id: '/_layout/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/home': {
      id: '/_layout/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutAuthenticatedHomeRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/_admin': {
      id: '/_layout/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/apps/$accountId/': {
      id: '/_layout/apps/$accountId/'
      path: '/apps/$accountId'
      fullPath: '/apps/$accountId/'
      preLoaderRoute: typeof LayoutAppsAccountIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/projects/': {
      id: '/_layout/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof LayoutAuthenticatedProjectsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/organizations/': {
      id: '/_layout/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/apps/$accountId/$gatewayId': {
      id: '/_layout/apps/$accountId/$gatewayId'
      path: '/apps/$accountId/$gatewayId'
      fullPath: '/apps/$accountId/$gatewayId'
      preLoaderRoute: typeof LayoutAppsAccountIdGatewayIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/projects/new': {
      id: '/_layout/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof LayoutAuthenticatedProjectsNewRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/projects/$id': {
      id: '/_layout/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof LayoutAuthenticatedProjectsIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/organizations/new': {
      id: '/_layout/_authenticated/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsNewRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/organizations/$id': {
      id: '/_layout/_authenticated/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/_admin/dashboard': {
      id: '/_layout/_authenticated/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedAdminDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRoute
    }
  }
}

interface LayoutAuthenticatedAdminRouteChildren {
  LayoutAuthenticatedAdminDashboardRoute: typeof LayoutAuthenticatedAdminDashboardRoute
}

const LayoutAuthenticatedAdminRouteChildren: LayoutAuthenticatedAdminRouteChildren =
  {
    LayoutAuthenticatedAdminDashboardRoute:
      LayoutAuthenticatedAdminDashboardRoute,
  }

const LayoutAuthenticatedAdminRouteWithChildren =
  LayoutAuthenticatedAdminRoute._addFileChildren(
    LayoutAuthenticatedAdminRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedAdminRoute: typeof LayoutAuthenticatedAdminRouteWithChildren
  LayoutAuthenticatedHomeRoute: typeof LayoutAuthenticatedHomeRoute
  LayoutAuthenticatedSettingsRoute: typeof LayoutAuthenticatedSettingsRoute
  LayoutAuthenticatedOrganizationsIdRoute: typeof LayoutAuthenticatedOrganizationsIdRoute
  LayoutAuthenticatedOrganizationsNewRoute: typeof LayoutAuthenticatedOrganizationsNewRoute
  LayoutAuthenticatedProjectsIdRoute: typeof LayoutAuthenticatedProjectsIdRoute
  LayoutAuthenticatedProjectsNewRoute: typeof LayoutAuthenticatedProjectsNewRoute
  LayoutAuthenticatedOrganizationsIndexRoute: typeof LayoutAuthenticatedOrganizationsIndexRoute
  LayoutAuthenticatedProjectsIndexRoute: typeof LayoutAuthenticatedProjectsIndexRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedAdminRoute: LayoutAuthenticatedAdminRouteWithChildren,
  LayoutAuthenticatedHomeRoute: LayoutAuthenticatedHomeRoute,
  LayoutAuthenticatedSettingsRoute: LayoutAuthenticatedSettingsRoute,
  LayoutAuthenticatedOrganizationsIdRoute:
    LayoutAuthenticatedOrganizationsIdRoute,
  LayoutAuthenticatedOrganizationsNewRoute:
    LayoutAuthenticatedOrganizationsNewRoute,
  LayoutAuthenticatedProjectsIdRoute: LayoutAuthenticatedProjectsIdRoute,
  LayoutAuthenticatedProjectsNewRoute: LayoutAuthenticatedProjectsNewRoute,
  LayoutAuthenticatedOrganizationsIndexRoute:
    LayoutAuthenticatedOrganizationsIndexRoute,
  LayoutAuthenticatedProjectsIndexRoute: LayoutAuthenticatedProjectsIndexRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutConfigRoute: typeof LayoutConfigRoute
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAppsIndexRoute: typeof LayoutAppsIndexRoute
  LayoutAppsAccountIdGatewayIdRoute: typeof LayoutAppsAccountIdGatewayIdRoute
  LayoutAppsAccountIdIndexRoute: typeof LayoutAppsAccountIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutConfigRoute: LayoutConfigRoute,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAppsIndexRoute: LayoutAppsIndexRoute,
  LayoutAppsAccountIdGatewayIdRoute: LayoutAppsAccountIdGatewayIdRoute,
  LayoutAppsAccountIdIndexRoute: LayoutAppsAccountIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
