/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutPublicRouteImport } from './routes/_layout/_public'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutAdminRouteImport } from './routes/_layout/_admin'
import { Route as LayoutPublicIndexRouteImport } from './routes/_layout/_public/index'
import { Route as LayoutPublicSkillRouteImport } from './routes/_layout/_public/skill'
import { Route as LayoutPublicLoginRouteImport } from './routes/_layout/_public/login'
import { Route as LayoutPublicAboutRouteImport } from './routes/_layout/_public/about'
import { Route as LayoutPublicAccountIdRouteImport } from './routes/_layout/_public/$accountId'
import { Route as LayoutAuthenticatedSettingsRouteImport } from './routes/_layout/_authenticated/settings'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/dashboard'
import { Route as LayoutAdminAdminRouteImport } from './routes/_layout/_admin/admin'
import { Route as LayoutPublicThingsIndexRouteImport } from './routes/_layout/_public/things/index'
import { Route as LayoutPublicAppsIndexRouteImport } from './routes/_layout/_public/apps/index'
import { Route as LayoutAuthenticatedSettingsIndexRouteImport } from './routes/_layout/_authenticated/settings/index'
import { Route as LayoutAuthenticatedOrganizationsIndexRouteImport } from './routes/_layout/_authenticated/organizations/index'
import { Route as LayoutAdminAdminIndexRouteImport } from './routes/_layout/_admin/admin/index'
import { Route as LayoutPublicThingsLiveRouteImport } from './routes/_layout/_public/things/live'
import { Route as LayoutPublicThingsThingIdRouteImport } from './routes/_layout/_public/things/$thingId'
import { Route as LayoutAuthenticatedThingsNewRouteImport } from './routes/_layout/_authenticated/things/new'
import { Route as LayoutAuthenticatedTenantNewRouteImport } from './routes/_layout/_authenticated/tenant/new'
import { Route as LayoutAuthenticatedTenantTenantIdRouteImport } from './routes/_layout/_authenticated/tenant/$tenantId'
import { Route as LayoutAuthenticatedSettingsSecurityRouteImport } from './routes/_layout/_authenticated/settings/security'
import { Route as LayoutAuthenticatedSettingsProfileRouteImport } from './routes/_layout/_authenticated/settings/profile'
import { Route as LayoutAuthenticatedSettingsAuthMethodsRouteImport } from './routes/_layout/_authenticated/settings/auth-methods'
import { Route as LayoutAuthenticatedOrganizationsNewRouteImport } from './routes/_layout/_authenticated/organizations/new'
import { Route as LayoutAuthenticatedOrganizationsSlugRouteImport } from './routes/_layout/_authenticated/organizations/$slug'
import { Route as LayoutAuthenticatedAcceptInvitationIdRouteImport } from './routes/_layout/_authenticated/accept-invitation.$id'
import { Route as LayoutAdminAdminSystemRouteImport } from './routes/_layout/_admin/admin/system'
import { Route as LayoutPublicAppsAccountIdIndexRouteImport } from './routes/_layout/_public/apps/$accountId/index'
import { Route as LayoutPublicAppsAccountIdGatewayIdRouteImport } from './routes/_layout/_public/apps/$accountId/$gatewayId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPublicRoute = LayoutPublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPublicIndexRoute = LayoutPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutPublicSkillRoute = LayoutPublicSkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutPublicLoginRoute = LayoutPublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutPublicAboutRoute = LayoutPublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutPublicAccountIdRoute = LayoutPublicAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutAuthenticatedSettingsRoute =
  LayoutAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAdminAdminRoute = LayoutAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutPublicThingsIndexRoute = LayoutPublicThingsIndexRouteImport.update({
  id: '/things/',
  path: '/things/',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutPublicAppsIndexRoute = LayoutPublicAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutAuthenticatedSettingsIndexRoute =
  LayoutAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedOrganizationsIndexRoute =
  LayoutAuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAdminAdminIndexRoute = LayoutAdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminAdminRoute,
} as any)
const LayoutPublicThingsLiveRoute = LayoutPublicThingsLiveRouteImport.update({
  id: '/things/live',
  path: '/things/live',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutPublicThingsThingIdRoute =
  LayoutPublicThingsThingIdRouteImport.update({
    id: '/things/$thingId',
    path: '/things/$thingId',
    getParentRoute: () => LayoutPublicRoute,
  } as any)
const LayoutAuthenticatedThingsNewRoute =
  LayoutAuthenticatedThingsNewRouteImport.update({
    id: '/things/new',
    path: '/things/new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedTenantNewRoute =
  LayoutAuthenticatedTenantNewRouteImport.update({
    id: '/tenant/new',
    path: '/tenant/new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedTenantTenantIdRoute =
  LayoutAuthenticatedTenantTenantIdRouteImport.update({
    id: '/tenant/$tenantId',
    path: '/tenant/$tenantId',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedSettingsSecurityRoute =
  LayoutAuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsProfileRoute =
  LayoutAuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsAuthMethodsRoute =
  LayoutAuthenticatedSettingsAuthMethodsRouteImport.update({
    id: '/auth-methods',
    path: '/auth-methods',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedOrganizationsNewRoute =
  LayoutAuthenticatedOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOrganizationsSlugRoute =
  LayoutAuthenticatedOrganizationsSlugRouteImport.update({
    id: '/organizations/$slug',
    path: '/organizations/$slug',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAcceptInvitationIdRoute =
  LayoutAuthenticatedAcceptInvitationIdRouteImport.update({
    id: '/accept-invitation/$id',
    path: '/accept-invitation/$id',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAdminAdminSystemRoute = LayoutAdminAdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => LayoutAdminAdminRoute,
} as any)
const LayoutPublicAppsAccountIdIndexRoute =
  LayoutPublicAppsAccountIdIndexRouteImport.update({
    id: '/apps/$accountId/',
    path: '/apps/$accountId/',
    getParentRoute: () => LayoutPublicRoute,
  } as any)
const LayoutPublicAppsAccountIdGatewayIdRoute =
  LayoutPublicAppsAccountIdGatewayIdRouteImport.update({
    id: '/apps/$accountId/$gatewayId',
    path: '/apps/$accountId/$gatewayId',
    getParentRoute: () => LayoutPublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutPublicIndexRoute
  '/admin': typeof LayoutAdminAdminRouteWithChildren
  '/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/settings': typeof LayoutAuthenticatedSettingsRouteWithChildren
  '/$accountId': typeof LayoutPublicAccountIdRoute
  '/about': typeof LayoutPublicAboutRoute
  '/login': typeof LayoutPublicLoginRoute
  '/skill': typeof LayoutPublicSkillRoute
  '/admin/system': typeof LayoutAdminAdminSystemRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/tenant/$tenantId': typeof LayoutAuthenticatedTenantTenantIdRoute
  '/tenant/new': typeof LayoutAuthenticatedTenantNewRoute
  '/things/new': typeof LayoutAuthenticatedThingsNewRoute
  '/things/$thingId': typeof LayoutPublicThingsThingIdRoute
  '/things/live': typeof LayoutPublicThingsLiveRoute
  '/admin/': typeof LayoutAdminAdminIndexRoute
  '/organizations/': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/settings/': typeof LayoutAuthenticatedSettingsIndexRoute
  '/apps/': typeof LayoutPublicAppsIndexRoute
  '/things/': typeof LayoutPublicThingsIndexRoute
  '/apps/$accountId/$gatewayId': typeof LayoutPublicAppsAccountIdGatewayIdRoute
  '/apps/$accountId/': typeof LayoutPublicAppsAccountIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutPublicIndexRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/$accountId': typeof LayoutPublicAccountIdRoute
  '/about': typeof LayoutPublicAboutRoute
  '/login': typeof LayoutPublicLoginRoute
  '/skill': typeof LayoutPublicSkillRoute
  '/admin/system': typeof LayoutAdminAdminSystemRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/tenant/$tenantId': typeof LayoutAuthenticatedTenantTenantIdRoute
  '/tenant/new': typeof LayoutAuthenticatedTenantNewRoute
  '/things/new': typeof LayoutAuthenticatedThingsNewRoute
  '/things/$thingId': typeof LayoutPublicThingsThingIdRoute
  '/things/live': typeof LayoutPublicThingsLiveRoute
  '/admin': typeof LayoutAdminAdminIndexRoute
  '/organizations': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/settings': typeof LayoutAuthenticatedSettingsIndexRoute
  '/apps': typeof LayoutPublicAppsIndexRoute
  '/things': typeof LayoutPublicThingsIndexRoute
  '/apps/$accountId/$gatewayId': typeof LayoutPublicAppsAccountIdGatewayIdRoute
  '/apps/$accountId': typeof LayoutPublicAppsAccountIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_admin': typeof LayoutAdminRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/_public': typeof LayoutPublicRouteWithChildren
  '/_layout/_admin/admin': typeof LayoutAdminAdminRouteWithChildren
  '/_layout/_authenticated/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/_layout/_authenticated/settings': typeof LayoutAuthenticatedSettingsRouteWithChildren
  '/_layout/_public/$accountId': typeof LayoutPublicAccountIdRoute
  '/_layout/_public/about': typeof LayoutPublicAboutRoute
  '/_layout/_public/login': typeof LayoutPublicLoginRoute
  '/_layout/_public/skill': typeof LayoutPublicSkillRoute
  '/_layout/_public/': typeof LayoutPublicIndexRoute
  '/_layout/_admin/admin/system': typeof LayoutAdminAdminSystemRoute
  '/_layout/_authenticated/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/_layout/_authenticated/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/_layout/_authenticated/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/_layout/_authenticated/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/_layout/_authenticated/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/_layout/_authenticated/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/_layout/_authenticated/tenant/$tenantId': typeof LayoutAuthenticatedTenantTenantIdRoute
  '/_layout/_authenticated/tenant/new': typeof LayoutAuthenticatedTenantNewRoute
  '/_layout/_authenticated/things/new': typeof LayoutAuthenticatedThingsNewRoute
  '/_layout/_public/things/$thingId': typeof LayoutPublicThingsThingIdRoute
  '/_layout/_public/things/live': typeof LayoutPublicThingsLiveRoute
  '/_layout/_admin/admin/': typeof LayoutAdminAdminIndexRoute
  '/_layout/_authenticated/organizations/': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/_layout/_authenticated/settings/': typeof LayoutAuthenticatedSettingsIndexRoute
  '/_layout/_public/apps/': typeof LayoutPublicAppsIndexRoute
  '/_layout/_public/things/': typeof LayoutPublicThingsIndexRoute
  '/_layout/_public/apps/$accountId/$gatewayId': typeof LayoutPublicAppsAccountIdGatewayIdRoute
  '/_layout/_public/apps/$accountId/': typeof LayoutPublicAppsAccountIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/$accountId'
    | '/about'
    | '/login'
    | '/skill'
    | '/admin/system'
    | '/accept-invitation/$id'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/tenant/$tenantId'
    | '/tenant/new'
    | '/things/new'
    | '/things/$thingId'
    | '/things/live'
    | '/admin/'
    | '/organizations/'
    | '/settings/'
    | '/apps/'
    | '/things/'
    | '/apps/$accountId/$gatewayId'
    | '/apps/$accountId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/$accountId'
    | '/about'
    | '/login'
    | '/skill'
    | '/admin/system'
    | '/accept-invitation/$id'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/tenant/$tenantId'
    | '/tenant/new'
    | '/things/new'
    | '/things/$thingId'
    | '/things/live'
    | '/admin'
    | '/organizations'
    | '/settings'
    | '/apps'
    | '/things'
    | '/apps/$accountId/$gatewayId'
    | '/apps/$accountId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_admin'
    | '/_layout/_authenticated'
    | '/_layout/_public'
    | '/_layout/_admin/admin'
    | '/_layout/_authenticated/dashboard'
    | '/_layout/_authenticated/settings'
    | '/_layout/_public/$accountId'
    | '/_layout/_public/about'
    | '/_layout/_public/login'
    | '/_layout/_public/skill'
    | '/_layout/_public/'
    | '/_layout/_admin/admin/system'
    | '/_layout/_authenticated/accept-invitation/$id'
    | '/_layout/_authenticated/organizations/$slug'
    | '/_layout/_authenticated/organizations/new'
    | '/_layout/_authenticated/settings/auth-methods'
    | '/_layout/_authenticated/settings/profile'
    | '/_layout/_authenticated/settings/security'
    | '/_layout/_authenticated/tenant/$tenantId'
    | '/_layout/_authenticated/tenant/new'
    | '/_layout/_authenticated/things/new'
    | '/_layout/_public/things/$thingId'
    | '/_layout/_public/things/live'
    | '/_layout/_admin/admin/'
    | '/_layout/_authenticated/organizations/'
    | '/_layout/_authenticated/settings/'
    | '/_layout/_public/apps/'
    | '/_layout/_public/things/'
    | '/_layout/_public/apps/$accountId/$gatewayId'
    | '/_layout/_public/apps/$accountId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_public': {
      id: '/_layout/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutPublicRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_admin': {
      id: '/_layout/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_public/': {
      id: '/_layout/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutPublicIndexRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_public/skill': {
      id: '/_layout/_public/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof LayoutPublicSkillRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_public/login': {
      id: '/_layout/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutPublicLoginRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_public/about': {
      id: '/_layout/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutPublicAboutRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_public/$accountId': {
      id: '/_layout/_public/$accountId'
      path: '/$accountId'
      fullPath: '/$accountId'
      preLoaderRoute: typeof LayoutPublicAccountIdRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_authenticated/settings': {
      id: '/_layout/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard': {
      id: '/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_admin/admin': {
      id: '/_layout/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminAdminRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/_public/things/': {
      id: '/_layout/_public/things/'
      path: '/things'
      fullPath: '/things/'
      preLoaderRoute: typeof LayoutPublicThingsIndexRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_public/apps/': {
      id: '/_layout/_public/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof LayoutPublicAppsIndexRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_authenticated/settings/': {
      id: '/_layout/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/organizations/': {
      id: '/_layout/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_admin/admin/': {
      id: '/_layout/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminAdminIndexRouteImport
      parentRoute: typeof LayoutAdminAdminRoute
    }
    '/_layout/_public/things/live': {
      id: '/_layout/_public/things/live'
      path: '/things/live'
      fullPath: '/things/live'
      preLoaderRoute: typeof LayoutPublicThingsLiveRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_public/things/$thingId': {
      id: '/_layout/_public/things/$thingId'
      path: '/things/$thingId'
      fullPath: '/things/$thingId'
      preLoaderRoute: typeof LayoutPublicThingsThingIdRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_authenticated/things/new': {
      id: '/_layout/_authenticated/things/new'
      path: '/things/new'
      fullPath: '/things/new'
      preLoaderRoute: typeof LayoutAuthenticatedThingsNewRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/tenant/new': {
      id: '/_layout/_authenticated/tenant/new'
      path: '/tenant/new'
      fullPath: '/tenant/new'
      preLoaderRoute: typeof LayoutAuthenticatedTenantNewRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/tenant/$tenantId': {
      id: '/_layout/_authenticated/tenant/$tenantId'
      path: '/tenant/$tenantId'
      fullPath: '/tenant/$tenantId'
      preLoaderRoute: typeof LayoutAuthenticatedTenantTenantIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/settings/security': {
      id: '/_layout/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/profile': {
      id: '/_layout/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsProfileRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/auth-methods': {
      id: '/_layout/_authenticated/settings/auth-methods'
      path: '/auth-methods'
      fullPath: '/settings/auth-methods'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsAuthMethodsRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/organizations/new': {
      id: '/_layout/_authenticated/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsNewRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/organizations/$slug': {
      id: '/_layout/_authenticated/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsSlugRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/accept-invitation/$id': {
      id: '/_layout/_authenticated/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof LayoutAuthenticatedAcceptInvitationIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_admin/admin/system': {
      id: '/_layout/_admin/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof LayoutAdminAdminSystemRouteImport
      parentRoute: typeof LayoutAdminAdminRoute
    }
    '/_layout/_public/apps/$accountId/': {
      id: '/_layout/_public/apps/$accountId/'
      path: '/apps/$accountId'
      fullPath: '/apps/$accountId/'
      preLoaderRoute: typeof LayoutPublicAppsAccountIdIndexRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_public/apps/$accountId/$gatewayId': {
      id: '/_layout/_public/apps/$accountId/$gatewayId'
      path: '/apps/$accountId/$gatewayId'
      fullPath: '/apps/$accountId/$gatewayId'
      preLoaderRoute: typeof LayoutPublicAppsAccountIdGatewayIdRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
  }
}

interface LayoutAdminAdminRouteChildren {
  LayoutAdminAdminSystemRoute: typeof LayoutAdminAdminSystemRoute
  LayoutAdminAdminIndexRoute: typeof LayoutAdminAdminIndexRoute
}

const LayoutAdminAdminRouteChildren: LayoutAdminAdminRouteChildren = {
  LayoutAdminAdminSystemRoute: LayoutAdminAdminSystemRoute,
  LayoutAdminAdminIndexRoute: LayoutAdminAdminIndexRoute,
}

const LayoutAdminAdminRouteWithChildren =
  LayoutAdminAdminRoute._addFileChildren(LayoutAdminAdminRouteChildren)

interface LayoutAdminRouteChildren {
  LayoutAdminAdminRoute: typeof LayoutAdminAdminRouteWithChildren
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminAdminRoute: LayoutAdminAdminRouteWithChildren,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutAuthenticatedSettingsRouteChildren {
  LayoutAuthenticatedSettingsAuthMethodsRoute: typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  LayoutAuthenticatedSettingsProfileRoute: typeof LayoutAuthenticatedSettingsProfileRoute
  LayoutAuthenticatedSettingsSecurityRoute: typeof LayoutAuthenticatedSettingsSecurityRoute
  LayoutAuthenticatedSettingsIndexRoute: typeof LayoutAuthenticatedSettingsIndexRoute
}

const LayoutAuthenticatedSettingsRouteChildren: LayoutAuthenticatedSettingsRouteChildren =
  {
    LayoutAuthenticatedSettingsAuthMethodsRoute:
      LayoutAuthenticatedSettingsAuthMethodsRoute,
    LayoutAuthenticatedSettingsProfileRoute:
      LayoutAuthenticatedSettingsProfileRoute,
    LayoutAuthenticatedSettingsSecurityRoute:
      LayoutAuthenticatedSettingsSecurityRoute,
    LayoutAuthenticatedSettingsIndexRoute:
      LayoutAuthenticatedSettingsIndexRoute,
  }

const LayoutAuthenticatedSettingsRouteWithChildren =
  LayoutAuthenticatedSettingsRoute._addFileChildren(
    LayoutAuthenticatedSettingsRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRoute
  LayoutAuthenticatedSettingsRoute: typeof LayoutAuthenticatedSettingsRouteWithChildren
  LayoutAuthenticatedAcceptInvitationIdRoute: typeof LayoutAuthenticatedAcceptInvitationIdRoute
  LayoutAuthenticatedOrganizationsSlugRoute: typeof LayoutAuthenticatedOrganizationsSlugRoute
  LayoutAuthenticatedOrganizationsNewRoute: typeof LayoutAuthenticatedOrganizationsNewRoute
  LayoutAuthenticatedTenantTenantIdRoute: typeof LayoutAuthenticatedTenantTenantIdRoute
  LayoutAuthenticatedTenantNewRoute: typeof LayoutAuthenticatedTenantNewRoute
  LayoutAuthenticatedThingsNewRoute: typeof LayoutAuthenticatedThingsNewRoute
  LayoutAuthenticatedOrganizationsIndexRoute: typeof LayoutAuthenticatedOrganizationsIndexRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedDashboardRoute: LayoutAuthenticatedDashboardRoute,
  LayoutAuthenticatedSettingsRoute:
    LayoutAuthenticatedSettingsRouteWithChildren,
  LayoutAuthenticatedAcceptInvitationIdRoute:
    LayoutAuthenticatedAcceptInvitationIdRoute,
  LayoutAuthenticatedOrganizationsSlugRoute:
    LayoutAuthenticatedOrganizationsSlugRoute,
  LayoutAuthenticatedOrganizationsNewRoute:
    LayoutAuthenticatedOrganizationsNewRoute,
  LayoutAuthenticatedTenantTenantIdRoute:
    LayoutAuthenticatedTenantTenantIdRoute,
  LayoutAuthenticatedTenantNewRoute: LayoutAuthenticatedTenantNewRoute,
  LayoutAuthenticatedThingsNewRoute: LayoutAuthenticatedThingsNewRoute,
  LayoutAuthenticatedOrganizationsIndexRoute:
    LayoutAuthenticatedOrganizationsIndexRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutPublicRouteChildren {
  LayoutPublicAccountIdRoute: typeof LayoutPublicAccountIdRoute
  LayoutPublicAboutRoute: typeof LayoutPublicAboutRoute
  LayoutPublicLoginRoute: typeof LayoutPublicLoginRoute
  LayoutPublicSkillRoute: typeof LayoutPublicSkillRoute
  LayoutPublicIndexRoute: typeof LayoutPublicIndexRoute
  LayoutPublicThingsThingIdRoute: typeof LayoutPublicThingsThingIdRoute
  LayoutPublicThingsLiveRoute: typeof LayoutPublicThingsLiveRoute
  LayoutPublicAppsIndexRoute: typeof LayoutPublicAppsIndexRoute
  LayoutPublicThingsIndexRoute: typeof LayoutPublicThingsIndexRoute
  LayoutPublicAppsAccountIdGatewayIdRoute: typeof LayoutPublicAppsAccountIdGatewayIdRoute
  LayoutPublicAppsAccountIdIndexRoute: typeof LayoutPublicAppsAccountIdIndexRoute
}

const LayoutPublicRouteChildren: LayoutPublicRouteChildren = {
  LayoutPublicAccountIdRoute: LayoutPublicAccountIdRoute,
  LayoutPublicAboutRoute: LayoutPublicAboutRoute,
  LayoutPublicLoginRoute: LayoutPublicLoginRoute,
  LayoutPublicSkillRoute: LayoutPublicSkillRoute,
  LayoutPublicIndexRoute: LayoutPublicIndexRoute,
  LayoutPublicThingsThingIdRoute: LayoutPublicThingsThingIdRoute,
  LayoutPublicThingsLiveRoute: LayoutPublicThingsLiveRoute,
  LayoutPublicAppsIndexRoute: LayoutPublicAppsIndexRoute,
  LayoutPublicThingsIndexRoute: LayoutPublicThingsIndexRoute,
  LayoutPublicAppsAccountIdGatewayIdRoute:
    LayoutPublicAppsAccountIdGatewayIdRoute,
  LayoutPublicAppsAccountIdIndexRoute: LayoutPublicAppsAccountIdIndexRoute,
}

const LayoutPublicRouteWithChildren = LayoutPublicRoute._addFileChildren(
  LayoutPublicRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutPublicRoute: typeof LayoutPublicRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutPublicRoute: LayoutPublicRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
