import { account, rateLimit, session, user, verification } from "./auth.js";
import {
  agentGrants,
  agents,
  apiKeys,
  auditEvents,
  auditRetentionHolds,
  custodyWallets,
  delayedExecutions,
  intentGenerations,
  operationArtifacts,
  operations,
  operationTombstones,
  ownerIntents,
  ownerNonces,
  ownerReceipts,
  quotaChanges,
  requestBuckets,
  spendCharges,
  sponsorReservations,
  tenants,
  walletPolicies,
} from "./domain.js";

export { account, rateLimit, session, user, verification } from "./auth.js";
export {
  agentGrants,
  agents,
  apiKeys,
  auditEvents,
  auditRetentionHolds,
  custodyWallets,
  delayedExecutions,
  intentGenerations,
  operationArtifacts,
  operations,
  operationTombstones,
  ownerIntents,
  ownerNonces,
  ownerReceipts,
  quotaChanges,
  requestBuckets,
  spendCharges,
  sponsorReservations,
  tenants,
  walletPolicies,
} from "./domain.js";

export const authSchema = { user, session, account, verification, rateLimit };
export const schema = {
  ...authSchema,
  apiKeys,
  agents,
  agentGrants,
  auditEvents,
  auditRetentionHolds,
  custodyWallets,
  delayedExecutions,
  operationArtifacts,
  operations,
  operationTombstones,
  intentGenerations,
  ownerIntents,
  ownerNonces,
  ownerReceipts,
  requestBuckets,
  quotaChanges,
  sponsorReservations,
  spendCharges,
  tenants,
  walletPolicies,
};
