import { z } from "zod";
import { partnerQuotaViewSchema } from "../quotas.js";
import { agentIdSchema, correlationIdSchema } from "./common.js";
import {
  balanceMoveRequestSchema,
  depositRequestSchema,
  historyPageSchema,
  historyQuerySchema,
  quoteResponseSchema,
  recoverRequestSchema,
  relayRequestSchema,
  signMessageRequestSchema,
  statusQuerySchema,
  statusResponseSchema,
  swapRequestSchema,
  transferRequestSchema,
  withdrawRequestSchema,
} from "./executions.js";
import {
  generateIntentRequestSchema,
  generateIntentResponseSchema,
  submitIntentRequestSchema,
} from "./intents.js";
import {
  acknowledgementSchema,
  agentListQuerySchema,
  agentPageSchema,
  agentViewSchema,
  approvalViewSchema,
  balanceQuerySchema,
  balancesViewSchema,
  budgetViewSchema,
  containmentQuerySchema,
  containmentViewSchema,
  createDeveloperKeySchema,
  createdDeveloperKeySchema,
  developerDashboardSchema,
  developerKeyListSchema,
  grantListViewSchema,
  limitsViewSchema,
  managedAgentPageSchema,
  managedAgentQuerySchema,
  networkViewSchema,
  policyHistoryQuerySchema,
  policyHistoryViewSchema,
  policyViewSchema,
  revocationViewSchema,
  scheduledPageSchema,
  scheduledQuerySchema,
  signatureDeliverySchema,
  timelockViewSchema,
  tokenListViewSchema,
  walletViewSchema,
  whoamiViewSchema,
} from "./views.js";

/**
 * The single definition of every `/v1` endpoint. The server mounts routes from it, OpenAPI is
 * generated from it and the SDK derives its method types from it, so none of them can drift.
 */

export type EndpointAuth = "apiKey" | "session" | "none";
export type EndpointMethod = "get" | "post" | "put" | "delete";

export type EndpointDefinition = {
  operationId: string;
  method: EndpointMethod;
  /** OpenAPI path template, e.g. `/v1/agents/{agentId}/swap`. */
  path: string;
  tag: string;
  summary: string;
  description?: string;
  auth: EndpointAuth;
  /**
   * Delegated work: the request must also carry `X-Grant-Token`, the token of the owner grant it
   * runs under. The API key alone never authorizes it.
   */
  grant?: true;
  params?: z.ZodObject;
  query?: z.ZodType;
  body?: z.ZodType;
  /** `Idempotency-Key` header: required for writes that create work, optional otherwise. */
  idempotency?: "required" | "optional";
  status: 200 | 201 | 202;
  response: z.ZodType;
  /** Kebab-case error codes this endpoint documents beyond generic validation and auth. */
  errors?: readonly string[];
};

function defineEndpoint<const E extends EndpointDefinition>(endpoint: E): E {
  return endpoint;
}

const agentParams = z.strictObject({ agentId: agentIdSchema });
const agentCorrelationParams = z.strictObject({
  agentId: agentIdSchema,
  correlationId: correlationIdSchema,
});
const executionResponse = z.union([statusResponseSchema, quoteResponseSchema]);
const executionErrors = [
  "agent-grant-required",
  "grant-action-denied",
  "grant-recipient-denied",
  "grant-recipient-required",
  "policy-not-ready",
  "policy-denied",
  "insufficient-balance",
  "amount-too-low",
  "route-unavailable",
  "wallet-busy",
  "wallet-frozen",
  "idempotency-conflict",
  "authorization-stale",
] as const;

export const endpoints = {
  getPartnerQuota: defineEndpoint({
    operationId: "getPartnerQuota",
    method: "get",
    path: "/v1/quotas",
    tag: "Partner",
    summary: "Read effective partner resource quotas and usage",
    auth: "apiKey",
    status: 200,
    response: partnerQuotaViewSchema,
  }),
  getDeveloperQuota: defineEndpoint({
    operationId: "getDeveloperQuota",
    method: "get",
    path: "/v1/developer/quotas",
    tag: "Developer",
    summary: "Read partner resource quotas and usage",
    auth: "session",
    status: 200,
    response: partnerQuotaViewSchema,
  }),

  // --------------------------------------------------------------------------------- intents
  generateIntent: defineEndpoint({
    operationId: "generateIntent",
    method: "post",
    path: "/v1/generate-intent",
    tag: "Owner intents",
    summary: "Generate an owner intent for signing",
    description:
      "Builds the exact payload the owner's wallet must sign for one owner action and returns it as `intent: {standard, payload}`. Sign `intent.payload` unchanged with the wallet named by `standard`, then call submit-intent with the wallet's output. `agent_create` creates a pending agent and returns its id.",
    auth: "apiKey",
    body: generateIntentRequestSchema,
    idempotency: "optional",
    status: 201,
    response: generateIntentResponseSchema,
    errors: [
      "agent-not-bound",
      "agent-not-found",
      "policy-revision-conflict",
      "grant-action-unknown",
      "grant-action-forbidden",
      "approval-closed",
      "owner-type-unsupported",
      "agent-quota-exceeded",
    ],
  }),
  submitIntent: defineEndpoint({
    operationId: "submitIntent",
    method: "post",
    path: "/v1/submit-intent",
    tag: "Owner intents",
    summary: "Submit a signed owner intent",
    description:
      "Submits the wallet's signature over a generated intent. `signedData.payload` must equal the generated payload. Resubmitting the same signature is idempotent. Returns the current status; poll GET /v1/status for settlement.",
    auth: "apiKey",
    body: submitIntentRequestSchema,
    status: 202,
    response: statusResponseSchema,
    errors: [
      "intent-not-found",
      "intent-expired",
      "intent-payload-mismatch",
      "intent-type-mismatch",
      "signature-invalid",
      "policy-revision-conflict",
      "sponsor-balance-insufficient",
      "sponsor-busy",
    ],
  }),
  getStatus: defineEndpoint({
    operationId: "getStatus",
    method: "get",
    path: "/v1/status",
    tag: "Status",
    summary: "Get the status of an intent or execution",
    description:
      "Reads the status of any correlation id and reconciles it with chain and provider state. `waitMs` long-polls until the status is terminal, needs a signature, or the wait ends.",
    auth: "apiKey",
    query: statusQuerySchema,
    status: 200,
    response: statusResponseSchema,
    errors: ["status-not-found"],
  }),
  getHistory: defineEndpoint({
    operationId: "getHistory",
    method: "get",
    path: "/v1/agents/{agentId}/history",
    tag: "Status",
    summary: "List an agent's intents and executions, newest first",
    auth: "apiKey",
    params: agentParams,
    query: historyQuerySchema,
    status: 200,
    response: historyPageSchema,
  }),

  // ---------------------------------------------------------------------------------- agents
  listAgents: defineEndpoint({
    operationId: "listAgents",
    method: "get",
    path: "/v1/agents",
    tag: "Agents",
    summary: "List agents",
    auth: "apiKey",
    query: agentListQuerySchema,
    status: 200,
    response: agentPageSchema,
  }),
  getAgent: defineEndpoint({
    operationId: "getAgent",
    method: "get",
    path: "/v1/agents/{agentId}",
    tag: "Agents",
    summary: "Get an agent",
    auth: "apiKey",
    params: agentParams,
    status: 200,
    response: agentViewSchema,
  }),
  getWallet: defineEndpoint({
    operationId: "getWallet",
    method: "get",
    path: "/v1/agents/{agentId}/wallet",
    tag: "Agents",
    summary: "Get the agent's custody wallet identity",
    auth: "apiKey",
    params: agentParams,
    status: 200,
    response: walletViewSchema,
  }),
  getBalances: defineEndpoint({
    operationId: "getBalances",
    method: "get",
    path: "/v1/agents/{agentId}/balances",
    tag: "Agents",
    summary: "Get the agent's balances",
    description:
      "`source=public` (default) and `confidential` list every non-zero asset. Amounts are atomic.",
    auth: "apiKey",
    params: agentParams,
    query: balanceQuerySchema,
    status: 200,
    response: balancesViewSchema,
  }),
  getPolicy: defineEndpoint({
    operationId: "getPolicy",
    method: "get",
    path: "/v1/agents/{agentId}/policy",
    tag: "Policy",
    summary: "Get the current policy revision",
    auth: "apiKey",
    params: agentParams,
    status: 200,
    response: policyViewSchema,
  }),
  getPolicyHistory: defineEndpoint({
    operationId: "getPolicyHistory",
    method: "get",
    path: "/v1/agents/{agentId}/policy/history",
    tag: "Policy",
    summary: "List signed policy revisions, newest first",
    auth: "apiKey",
    params: agentParams,
    query: policyHistoryQuerySchema,
    status: 200,
    response: policyHistoryViewSchema,
  }),
  getLimits: defineEndpoint({
    operationId: "getLimits",
    method: "get",
    path: "/v1/agents/{agentId}/limits",
    tag: "Policy",
    summary: "Get hard limits OutLayer enforces for the agent",
    auth: "apiKey",
    params: agentParams,
    status: 200,
    response: limitsViewSchema,
  }),
  listGrants: defineEndpoint({
    operationId: "listGrants",
    method: "get",
    path: "/v1/agents/{agentId}/grants",
    tag: "Grants",
    summary: "List every grant for the agent, including revoked ones",
    auth: "apiKey",
    params: agentParams,
    status: 200,
    response: grantListViewSchema,
  }),
  getTimelock: defineEndpoint({
    operationId: "getTimelock",
    method: "get",
    path: "/v1/agents/{agentId}/timelock",
    tag: "Grants",
    summary: "Get the execution timelock and how many executions it holds",
    auth: "apiKey",
    params: agentParams,
    status: 200,
    response: timelockViewSchema,
  }),
  listScheduledExecutions: defineEndpoint({
    operationId: "listScheduledExecutions",
    method: "get",
    path: "/v1/agents/{agentId}/timelock/scheduled",
    tag: "Grants",
    summary: "List executions the timelock holds, earliest release first",
    auth: "apiKey",
    params: agentParams,
    query: scheduledQuerySchema,
    status: 200,
    response: scheduledPageSchema,
  }),
  getBudget: defineEndpoint({
    operationId: "getBudget",
    method: "get",
    path: "/v1/agents/{agentId}/budget",
    tag: "Grants",
    summary: "Get the USD spend caps and how much of each is used",
    auth: "apiKey",
    params: agentParams,
    status: 200,
    response: budgetViewSchema,
  }),
  getContainment: defineEndpoint({
    operationId: "getContainment",
    method: "get",
    path: "/v1/agents/{agentId}/containment",
    tag: "Grants",
    summary: "Get the agent's API enforcement state and open work",
    auth: "apiKey",
    params: agentParams,
    query: containmentQuerySchema,
    status: 200,
    response: containmentViewSchema,
  }),
  listApprovals: defineEndpoint({
    operationId: "listApprovals",
    method: "get",
    path: "/v1/agents/{agentId}/approvals",
    tag: "Approvals",
    summary: "List requests waiting for approval",
    auth: "apiKey",
    params: agentParams,
    status: 200,
    response: z.strictObject({ data: z.array(approvalViewSchema) }),
  }),
  getApproval: defineEndpoint({
    operationId: "getApproval",
    method: "get",
    path: "/v1/agents/{agentId}/approvals/{approvalId}",
    tag: "Approvals",
    summary: "Get one approval request",
    auth: "apiKey",
    params: z.strictObject({ agentId: agentIdSchema, approvalId: z.uuid() }),
    status: 200,
    response: approvalViewSchema,
  }),
  getAddress: defineEndpoint({
    operationId: "getAddress",
    method: "get",
    path: "/v1/agents/{agentId}/addresses/{chain}",
    tag: "Agents",
    summary: "Get the custody wallet's address on a chain",
    auth: "apiKey",
    params: z.strictObject({ agentId: agentIdSchema, chain: z.string().min(1).max(64) }),
    status: 200,
    response: z.strictObject({ chain: z.string(), address: z.string() }).passthrough(),
  }),
  listProviderRecords: defineEndpoint({
    operationId: "listProviderRecords",
    method: "get",
    path: "/v1/agents/{agentId}/provider/{kind}",
    tag: "Agents",
    summary: "Read OutLayer request, audit or deposit records for reconciliation",
    auth: "apiKey",
    params: z.strictObject({
      agentId: agentIdSchema,
      kind: z.enum(["requests", "audit", "deposits", "deposit-history"]),
    }),
    query: z.strictObject({
      limit: z.coerce.number().int().min(1).max(100).optional(),
      offset: z.coerce.number().int().nonnegative().max(10_000).optional(),
      type: z.string().min(1).max(256).optional(),
    }),
    status: 200,
    response: z.strictObject({ data: z.unknown() }),
  }),

  // ------------------------------------------------------------------------------ executions
  swap: defineEndpoint({
    operationId: "swap",
    method: "post",
    path: "/v1/agents/{agentId}/swap",
    tag: "Executions",
    summary: "Swap one asset for another",
    description:
      "Requires `X-Grant-Token` for a grant that allows `swap`. With `dry: true` returns a quote and needs no `Idempotency-Key`.",
    auth: "apiKey",
    grant: true,
    params: agentParams,
    body: swapRequestSchema,
    idempotency: "required",
    status: 202,
    response: executionResponse,
    errors: executionErrors,
  }),
  withdraw: defineEndpoint({
    operationId: "withdraw",
    method: "post",
    path: "/v1/agents/{agentId}/withdraw",
    tag: "Executions",
    summary: "Withdraw an asset to an address on any supported chain",
    description:
      "Requires `X-Grant-Token` for a grant that allows `withdraw`. With `dry: true` previews fees and needs no `Idempotency-Key`.",
    auth: "apiKey",
    grant: true,
    params: agentParams,
    body: withdrawRequestSchema,
    idempotency: "required",
    status: 202,
    response: executionResponse,
    errors: executionErrors,
  }),
  transfer: defineEndpoint({
    operationId: "transfer",
    method: "post",
    path: "/v1/agents/{agentId}/transfer",
    tag: "Executions",
    summary: "Transfer an asset to another NEAR Intents account",
    description:
      "Requires `X-Grant-Token` for a grant that allows `intents_transfer`, or `confidential_transfer` when `confidential` is true.",
    auth: "apiKey",
    grant: true,
    params: agentParams,
    body: transferRequestSchema,
    idempotency: "required",
    status: 202,
    response: statusResponseSchema,
    errors: executionErrors,
  }),
  shield: defineEndpoint({
    operationId: "shield",
    method: "post",
    path: "/v1/agents/{agentId}/shield",
    tag: "Executions",
    summary: "Move a public balance to the confidential shard",
    auth: "apiKey",
    grant: true,
    params: agentParams,
    body: balanceMoveRequestSchema,
    idempotency: "required",
    status: 202,
    response: statusResponseSchema,
    errors: executionErrors,
  }),
  unshield: defineEndpoint({
    operationId: "unshield",
    method: "post",
    path: "/v1/agents/{agentId}/unshield",
    tag: "Executions",
    summary: "Move a confidential balance back to public",
    auth: "apiKey",
    grant: true,
    params: agentParams,
    body: balanceMoveRequestSchema,
    idempotency: "required",
    status: 202,
    response: statusResponseSchema,
    errors: executionErrors,
  }),
  confidentialDeposit: defineEndpoint({
    operationId: "confidentialDeposit",
    method: "post",
    path: "/v1/agents/{agentId}/confidential-deposit",
    tag: "Executions",
    summary: "Deposit a public balance into the confidential shard",
    auth: "apiKey",
    grant: true,
    params: agentParams,
    body: balanceMoveRequestSchema,
    idempotency: "required",
    status: 202,
    response: statusResponseSchema,
    errors: executionErrors,
  }),
  deposit: defineEndpoint({
    operationId: "deposit",
    method: "post",
    path: "/v1/agents/{agentId}/deposit",
    tag: "Executions",
    summary: "Get a deposit address that funds the agent from another chain",
    description:
      "Requires `X-Grant-Token` for a grant that allows `cross_chain_deposit`. The status reads `PENDING_DEPOSIT` with `details.depositAddress` until funds arrive.",
    auth: "apiKey",
    grant: true,
    params: agentParams,
    body: depositRequestSchema,
    idempotency: "required",
    status: 202,
    response: statusResponseSchema,
    errors: executionErrors,
  }),
  recover: defineEndpoint({
    operationId: "recover",
    method: "post",
    path: "/v1/agents/{agentId}/recover",
    tag: "Executions",
    summary: "Dispatch an UNCERTAIN execution that provably never reached the provider",
    description:
      "Only for executions with no provider reference and no dispatch commitment. `request` must equal the original body, `Idempotency-Key` the original key, and `X-Grant-Token` the token of the grant that admitted it.",
    auth: "apiKey",
    grant: true,
    params: agentParams,
    body: recoverRequestSchema,
    idempotency: "required",
    status: 202,
    response: statusResponseSchema,
    errors: ["operation-not-recoverable", "operation-recovery-unavailable", "idempotency-conflict"],
  }),
  signMessage: defineEndpoint({
    operationId: "signMessage",
    method: "post",
    path: "/v1/agents/{agentId}/sign-message",
    tag: "Signing",
    summary: "Sign an identity challenge with the agent's custody key",
    description:
      "NEP-413 (`chain: near`) or EIP-191 (EVM chains) over a canonical identity challenge. Requires `X-Grant-Token` for a grant that allows `sign:near_message` or `sign:evm_message`. Read the signature with GET /signatures/{correlationId}, then acknowledge it.",
    auth: "apiKey",
    grant: true,
    params: agentParams,
    body: signMessageRequestSchema,
    idempotency: "required",
    status: 202,
    response: statusResponseSchema,
  }),
  getSignature: defineEndpoint({
    operationId: "getSignature",
    method: "get",
    path: "/v1/agents/{agentId}/signatures/{correlationId}",
    tag: "Signing",
    summary: "Read a completed signature",
    auth: "apiKey",
    grant: true,
    params: agentCorrelationParams,
    status: 200,
    response: signatureDeliverySchema,
    errors: ["signing-artifact-not-found", "signing-artifact-expired"],
  }),
  acknowledgeSignature: defineEndpoint({
    operationId: "acknowledgeSignature",
    method: "post",
    path: "/v1/agents/{agentId}/signatures/{correlationId}/ack",
    tag: "Signing",
    summary: "Erase a delivered signature from the server",
    auth: "apiKey",
    grant: true,
    params: agentCorrelationParams,
    status: 200,
    response: acknowledgementSchema,
  }),
  relay: defineEndpoint({
    operationId: "relay",
    method: "post",
    path: "/v1/agents/{agentId}/relay",
    tag: "Signing",
    summary: "Relay an owner-signed NEP-366 delegate to an allowlisted receiver",
    auth: "apiKey",
    params: agentParams,
    body: relayRequestSchema,
    idempotency: "required",
    status: 202,
    response: statusResponseSchema,
    errors: ["sponsor-balance-insufficient", "transaction-unconfirmed"],
  }),

  // ------------------------------------------------------------------------------------ meta
  getTokens: defineEndpoint({
    operationId: "getTokens",
    method: "get",
    path: "/v1/tokens",
    tag: "Meta",
    summary: "List the assets agents can hold and trade, with USD prices",
    description:
      "Exactly the custody provider's (OutLayer) supported assets, with chain and price from the public 1Click token list. `assetId` is the value executions take. Public; the provider list is cached for 30 minutes and prices for one.",
    auth: "none",
    status: 200,
    response: tokenListViewSchema,
  }),
  getNetwork: defineEndpoint({
    operationId: "getNetwork",
    method: "get",
    path: "/v1/network",
    tag: "Meta",
    summary: "Get the network and supported owner types",
    auth: "none",
    status: 200,
    response: networkViewSchema,
  }),
  whoami: defineEndpoint({
    operationId: "whoami",
    method: "get",
    path: "/v1/whoami",
    tag: "Meta",
    summary: "Identify the calling API key",
    auth: "apiKey",
    status: 200,
    response: whoamiViewSchema,
  }),

  // ------------------------------------------------------------------------------- developer
  listDeveloperKeys: defineEndpoint({
    operationId: "listDeveloperKeys",
    method: "get",
    path: "/v1/developer/keys",
    tag: "Developer",
    summary: "List API keys",
    auth: "session",
    status: 200,
    response: developerKeyListSchema,
  }),
  createDeveloperKey: defineEndpoint({
    operationId: "createDeveloperKey",
    method: "post",
    path: "/v1/developer/keys",
    tag: "Developer",
    summary: "Create an API key; the token is returned once",
    auth: "session",
    body: createDeveloperKeySchema,
    status: 201,
    response: createdDeveloperKeySchema,
    errors: ["api-key-quota-exceeded", "fresh-login-required", "invalid-origin"],
  }),
  revokeDeveloperKey: defineEndpoint({
    operationId: "revokeDeveloperKey",
    method: "delete",
    path: "/v1/developer/keys/{keyId}",
    tag: "Developer",
    summary: "Revoke an API key",
    auth: "session",
    params: z.strictObject({ keyId: z.string().min(1).max(64) }),
    status: 200,
    response: revocationViewSchema,
  }),
  getDeveloperDashboard: defineEndpoint({
    operationId: "getDeveloperDashboard",
    method: "get",
    path: "/v1/developer/dashboard",
    tag: "Developer",
    summary: "Get all-time tenant counts",
    auth: "session",
    status: 200,
    response: developerDashboardSchema,
  }),
  listManagedAgents: defineEndpoint({
    operationId: "listManagedAgents",
    method: "get",
    path: "/v1/developer/agents",
    tag: "Developer",
    summary: "List the tenant's agents",
    auth: "session",
    query: managedAgentQuerySchema,
    status: 200,
    response: managedAgentPageSchema,
  }),
  getManagedAgentPolicy: defineEndpoint({
    operationId: "getManagedAgentPolicy",
    method: "get",
    path: "/v1/developer/agents/{agentId}/policy",
    tag: "Developer",
    summary: "Get an agent's current policy",
    auth: "session",
    params: agentParams,
    status: 200,
    response: policyViewSchema,
  }),
  getManagedAgentLimits: defineEndpoint({
    operationId: "getManagedAgentLimits",
    method: "get",
    path: "/v1/developer/agents/{agentId}/limits",
    tag: "Developer",
    summary: "Get an agent's enforced limits",
    auth: "session",
    params: agentParams,
    status: 200,
    response: limitsViewSchema,
  }),
  getManagedAgentBudget: defineEndpoint({
    operationId: "getManagedAgentBudget",
    method: "get",
    path: "/v1/developer/agents/{agentId}/budget",
    tag: "Developer",
    summary: "Get an agent's USD spend caps and usage",
    auth: "session",
    params: agentParams,
    status: 200,
    response: budgetViewSchema,
  }),
  getManagedAgentTimelock: defineEndpoint({
    operationId: "getManagedAgentTimelock",
    method: "get",
    path: "/v1/developer/agents/{agentId}/timelock",
    tag: "Developer",
    summary: "Get an agent's execution timelock",
    auth: "session",
    params: agentParams,
    status: 200,
    response: timelockViewSchema,
  }),
  listManagedAgentScheduledExecutions: defineEndpoint({
    operationId: "listManagedAgentScheduledExecutions",
    method: "get",
    path: "/v1/developer/agents/{agentId}/timelock/scheduled",
    tag: "Developer",
    summary: "List an agent's timelocked executions, earliest release first",
    auth: "session",
    params: agentParams,
    query: scheduledQuerySchema,
    status: 200,
    response: scheduledPageSchema,
  }),
} as const;

export type Endpoints = typeof endpoints;
export type EndpointName = keyof Endpoints;
